apiVersion: v1
kind: Service
metadata:
  name: my-djanjo-app-service
spec:
  type: NodePort
  selector:
    app: my-djanjo-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080        # access via http://<EC2_IP>:30080
