AWSTemplateFormatVersion: '2010-09-09'
Description: CloudVision POC — EC2 + k3s v1.28

Parameters:
  ProjectName:
    Type: String
    Default: my-djanjo-app

  InstanceType:
    Type: String
    Default: t3.medium

  ImageId:
    Type: String
    Default: ami-0d05471b100e9083f

  KeyName:
    Type: String
    Description: Your AWS Academy Key Pair name

Resources:

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH HTTP and k3s
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 6443
          ToPort: 6443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 30000
          ToPort: 32767
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-k3s-server"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_SELINUX_RPM=true INSTALL_K3S_VERSION="v1.28.15+k3s1" sh -
          systemctl enable k3s
          sleep 60
          echo 'export PATH=$PATH:/usr/local/bin' > /etc/profile.d/k3s.sh
          mkdir -p /home/ec2-user/.kube
          cp /etc/rancher/k3s/k3s.yaml /home/ec2-user/.kube/config
          chown -R ec2-user:ec2-user /home/ec2-user/.kube
          chmod 644 /home/ec2-user/.kube/config
          timeout 180 bash -c 'until /usr/local/bin/k3s kubectl get nodes 2>/dev/null | grep -q Ready; do sleep 10; done'
          echo "k3s setup complete" > /tmp/k3s-ready

Outputs:
  InstancePublicIP:
    Value: !GetAtt EC2Instance.PublicIp
    Description: Public IP of the k3s server
    Export:
      Name: K3sPublicIP

  InstanceId:
    Value: !Ref EC2Instance
    Description: EC2 Instance ID
    Export:
      Name: K3sInstanceId
